spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
  redis:
    host: ${REDIS_HOST:localhost}
    
  profiles: docker